# Generated by Django 5.2.3 on 2025-06-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productsall',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
            ],
        ),
    ]
